name: Update LazyVim From Upstream And Fix Hashes

on:
  schedule:
    # Run daily at 3 AM UTC
    - cron: '0 3 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Update from upstream
        run: |
          git remote add upstream https://github.com/pfassina/lazyvim-nix.git
          git config pull.rebase true
          git pull remote upstream

      - uses: DeterminateSystems/determinate-nix-action@v3

      - run: nix flake check -L

      - name: Fix hash mismatches
        if: failure()
        run: |
          determinate-nixd fix hashes --auto-apply

          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "[dependabot skip] Fix hashes"
            git push
          fi